import { describe, expect, it } from 'vitest'
import { estimerDensite, hauteurDensite, modeleExploration, payloadPourCarte, positionDensite } from '../indicateurs/explorationModel'
import { normalizeComparisonFacet } from '../indicateurs/familySeam'
import { metadonneesThemesFixtures } from '../payload/fixtures'
import type { Indicateur, Territoire } from '../payload/types'

const territoires: Territoire[] = [
  { territoire: 'a', type: 'commune', nom: 'Alpha', departement: '22', epci: 'e' }, { territoire: 'b', type: 'commune', nom: 'Beta', departement: '22', epci: 'e' }, { territoire: 'c', type: 'commune', nom: 'Gamma', departement: '29', epci: 'f' }, { territoire: 'd', type: 'commune', nom: 'Delta', departement: '29', epci: 'f' },
  { territoire: 'e', type: 'epci', nom: 'E Bretagne', departement: null, epci: null }, { territoire: 'f', type: 'epci', nom: 'F Bretagne', departement: null, epci: null }, { territoire: '22', type: 'departement', nom: 'Côtes-d’Armor', departement: null, epci: null }, { territoire: '29', type: 'departement', nom: 'Finistère', departement: null, epci: null },
]
const facts = (id: string, value: number | null, type: Indicateur['type'] = 'commune'): Indicateur => ({ territoire: id, type, theme: 'demographie', key: 'densite', detail: null, value, unit: 'hab./km²', rang_epci: null, rang_dep: null, rang_reg: null, rang_epci_n: null, rang_dep_n: null, rang_reg_n: null, vintage_source: 'INSEE', vintage_version: '2023', vintage_date_reference: '2023-01-01', vintage_date_publication: '2024-01-01' })
const facet = (requested: object = {}) => normalizeComparisonFacet(metadonneesThemesFixtures.demographie.indicator_pages!.densite, requested, 'demographie')

describe('modèle pur de Page d’indicateur', () => {
  it('keeps Bretagne EPCI and département scopes populated', () => { expect(modeleExploration([facts('e', 10, 'epci'), facts('f', 20, 'epci')], facet(), territoires, { niveau: 'epci' }).rows).toHaveLength(2); expect(modeleExploration([facts('22', 10, 'departement'), facts('29', 20, 'departement')], facet(), territoires, { niveau: 'departement' }).rows).toHaveLength(2) })
  it('filters communes and removes incompatible scope state at other levels', () => { const factsAll = [facts('a', 10), facts('b', 20), facts('c', 30)]; expect(modeleExploration(factsAll, facet(), territoires, { niveau: 'commune', departement: '22' }).rows).toHaveLength(2); const result = modeleExploration([facts('e', 10, 'epci')], facet(), territoires, { niveau: 'epci', departement: '22', epci: 'e' }); expect(result.state.departement).toBeUndefined(); expect(result.state.epci).toBeUndefined() })
  it('computes median, direction and ranks from the resolved facet', () => { const metadata = structuredClone(metadonneesThemesFixtures.demographie); metadata.indicator_pages!.densite.direction = 'low'; const lowFacet = normalizeComparisonFacet(metadata.indicator_pages!.densite, {}, 'demographie'); const result = modeleExploration([facts('a', 10), facts('b', 10), facts('c', 30), facts('d', 40)], lowFacet, territoires, { niveau: 'commune', tri: 'valeur', ordre: 'desc' }); expect(result.median).toBe(20); expect(result.direction).toBe('low'); expect(result.rows.map((row) => row.rang)).toEqual([4, 3, 1, 1]) })
  it('samples finite density coordinates', () => { const density = estimerDensite([10, 20, 30]); expect(density.every((point) => Number.isFinite(point.x) && Number.isFinite(point.density))).toBe(true); expect(positionDensite(density, 20)).toBeCloseTo(50); expect(hauteurDensite(density, 20)).not.toBeNull() })
  it('uses the same resolved facet for map filtering including dimensions', () => { const resolved = { ...facet(), detail: 'F', sex: 'F' as const, dimension: 'women', labels: { F: 'Femmes' } }; const source = { territoires, indicateurs: [facts('a', 10), facts('b', 20)], histoires: [], apercu: null, runReport: null, vintages: null, programmes: null }; const result = payloadPourCarte(source, resolved, 'commune', '22'); expect(result.indicateurs).toHaveLength(0) })
  it('presents ties, null values and empty scopes honestly', () => { const tied = modeleExploration([facts('a', 0), facts('b', 0), facts('c', null)], facet(), territoires, { niveau: 'commune', territoire: 'c' }); expect(tied.high.count).toBe(2); expect(tied.median).toBe(0); expect(tied.markerX).toBeNull(); const empty = modeleExploration([], facet(), territoires, { niveau: 'commune' }); expect(empty.rows).toHaveLength(0); expect(empty.median).toBeNull() })
})
