import { describe, expect, it } from 'vitest'
import { estimerDensite, hauteurDensite, modeleExploration, payloadPourCarte, positionDensite } from '../indicateurs/explorationModel'
import { metadonneesThemesFixtures } from '../payload/fixtures'
import type { Indicateur, Territoire } from '../payload/types'

const territoires: Territoire[] = [
  { territoire: 'a', type: 'commune', nom: 'Alpha', departement: '22', epci: 'e' }, { territoire: 'b', type: 'commune', nom: 'Beta', departement: '22', epci: 'e' }, { territoire: 'c', type: 'commune', nom: 'Gamma', departement: '29', epci: 'f' }, { territoire: 'd', type: 'commune', nom: 'Delta', departement: '29', epci: 'f' },
  { territoire: 'e', type: 'epci', nom: 'E Bretagne', departement: null, epci: null }, { territoire: 'f', type: 'epci', nom: 'F Bretagne', departement: null, epci: null },
  { territoire: '22', type: 'departement', nom: 'Côtes-d’Armor', departement: null, epci: null }, { territoire: '29', type: 'departement', nom: 'Finistère', departement: null, epci: null },
]
const facts = (id: string, value: number | null, type: Indicateur['type'] = 'commune'): Indicateur => ({ territoire: id, type, theme: 'demographie', key: 'densite', detail: null, value, unit: 'hab./km²', rang_epci: null, rang_dep: null, rang_reg: null, rang_epci_n: null, rang_dep_n: null, rang_reg_n: null, vintage_source: 'INSEE', vintage_version: '2023', vintage_date_reference: '2023-01-01', vintage_date_publication: '2024-01-01' })

describe('modèle pur de Page d’indicateur', () => {
  it('keeps Bretagne EPCI and département scopes populated', () => { const result = modeleExploration([facts('e', 10, 'epci'), facts('f', 20, 'epci')], metadonneesThemesFixtures.demographie, territoires, { niveau: 'epci' }, undefined, 'densite'); expect(result.rows).toHaveLength(2); const dep = modeleExploration([facts('22', 10, 'departement'), facts('29', 20, 'departement')], metadonneesThemesFixtures.demographie, territoires, { niveau: 'departement' }, undefined, 'densite'); expect(dep.rows).toHaveLength(2) })
  it('filters communes and removes incompatible scope state at other levels', () => { const metadata = metadonneesThemesFixtures.demographie; const factsAll = [facts('a', 10), facts('b', 20), facts('c', 30)]; expect(modeleExploration(factsAll, metadata, territoires, { niveau: 'commune', departement: '22' }, undefined, 'densite').rows).toHaveLength(2); const result = modeleExploration([facts('e', 10, 'epci')], metadata, territoires, { niveau: 'epci', departement: '22', epci: 'e' }, undefined, 'densite'); expect(result.state.departement).toBeUndefined(); expect(result.state.epci).toBeUndefined() })
  it('computes a true even median and typed high/low ranks with ties', () => { const metadata = structuredClone(metadonneesThemesFixtures.demographie); metadata.indicator_pages!.densite.direction = 'low'; const result = modeleExploration([facts('a', 10), facts('b', 10), facts('c', 30), facts('d', 40)], metadata, territoires, { niveau: 'commune', tri: 'valeur', ordre: 'desc' }, undefined, 'densite'); expect(result.median).toBe(20); expect(result.direction).toBe('low'); expect(result.rows.map((row) => row.rang)).toEqual([4, 3, 1, 1]) })
  it('samples a finite KDE on a value-domain grid and positions selections', () => { const density = estimerDensite([10, 20, 30]); expect(density).toHaveLength(64); expect(density.every((point) => Number.isFinite(point.x) && Number.isFinite(point.density) && point.density >= 0)).toBe(true); expect(new Set(density.map((point) => point.x)).size).toBe(64); expect(positionDensite(density, 20)).toBeCloseTo(50); expect(estimerDensite([2, 2])[0].x).toBe(2) })
  it('returns normalized finite plot coordinates, including equal-value distributions', () => { const density = estimerDensite([2, 2]); expect(density.every((point) => Number.isFinite(point.y) && point.y >= 0 && point.y <= 100)).toBe(true); const result = modeleExploration([facts('a', 10), facts('b', 20), facts('c', 30)], metadonneesThemesFixtures.demographie, territoires, { niveau: 'commune', territoire: 'b' }, undefined, 'densite'); expect(result.markerX).toBeGreaterThan(0); expect(result.markerX).toBeLessThan(100); expect(result.markerY).toBeCloseTo(hauteurDensite(result.density, 20)!); expect(result.markerY).not.toBe(34) })
  it('exposes comparison size and honors neutral URL sort plus rank sort', () => { const metadata = metadonneesThemesFixtures.demographie; const result = modeleExploration([facts('a', 10), facts('b', 20), facts('c', 30)], metadata, territoires, { niveau: 'commune', tri: 'nom', ordre: 'asc' }, undefined, 'densite'); expect(result.rows[0].territoire.nom).toBe('Alpha'); expect(result.rows[0].rangTaille).toBe(3); expect(modeleExploration([facts('a', 10), facts('b', 20), facts('c', 30)], metadata, territoires, { niveau: 'commune', tri: 'rang', ordre: 'asc' }, undefined, 'densite').rows[0].rang).toBe(1) })
  it('builds département and EPCI map payloads without mutating shared facts', () => { const source = { territoires, indicateurs: [facts('a', 10), facts('b', 20), facts('c', 30), facts('d', 40)], histoires: [], apercu: null, runReport: null, vintages: null, programmes: null, themeMetadata: { demographie: metadonneesThemesFixtures.demographie } }; expect(payloadPourCarte(source, 'demographie', 'densite', 'commune', '22').indicateurs.map((fact) => fact.territoire)).toEqual(['a', 'b']); expect(payloadPourCarte(source, 'demographie', 'densite', 'commune', undefined, 'f').indicateurs.map((fact) => fact.territoire)).toEqual(['c', 'd']); expect(source.indicateurs).toHaveLength(4) })
  it('presents ties as counts, unique extremes as linkable rows, and handles null/empty/zero/highlight exclusion', () => { const metadata = metadonneesThemesFixtures.demographie; const tied = modeleExploration([facts('a', 0), facts('b', 0), facts('c', null)], metadata, territoires, { niveau: 'commune', territoire: 'c' }, undefined, 'densite'); expect(tied.high.count).toBe(2); expect(tied.high.rows).toHaveLength(0); expect(tied.median).toBe(0); expect(tied.markerX).toBeNull(); const empty = modeleExploration([], metadata, territoires, { niveau: 'commune' }, undefined, 'densite'); expect(empty.rows).toHaveLength(0); expect(empty.median).toBeNull() })
  it('compares a distribution through its declared summary while retaining the selected signature', () => {
    const metadata = structuredClone(metadonneesThemesFixtures.demographie)
    metadata.indicator_pages!.densite = { ...metadata.indicator_pages!.densite, family: 'distribution', summary: { indicator: 'densite', detail: null, label: 'Facette résumée', unit: 'u' } }
    const signature = (id: string, detail: string, value: number): Indicateur => ({ ...facts(id, value), detail })
    const result = modeleExploration([facts('a', 10), facts('b', 20), signature('a', 'A', .25), signature('a', 'B', .75)], metadata, territoires, { niveau: 'commune', territoire: 'a' }, undefined, 'densite')
    expect(result.rows.map((row) => row.value)).toEqual([10, 20])
    expect(result.signature).toEqual([{ detail: 'A', value: .25 }, { detail: 'B', value: .75 }])
    expect(result.summaryLabel).toBe('Facette résumée')
  })
})
